name: CI

on:
   push:
     branches:
     - main
   pull_request:
     branches:
     - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libzfs
      run: |
        sudo apt-get update
        sudo apt-get install -y libzfslinux-dev

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
